version: "3"
services: 
    db:
        image: mysql
        container_name: mysql-container 
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: password
        volumes: 
            - ./banco:/var/lib/mysql 
        restart: always 
    webapp:
        